export const dataFake = [ ///titre, description, origin, fournisseur, stock, price, image
    {
        id: 1,
        category: "informatique",
        titre: "Telephone Portable",
        image: "image.jpg",
        description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Quidem, odio minima odit placeat sapiente est omnis ducimus error qui voluptatum voluptas! Rem voluptatem magni ullam non facere dolorem iure modi.",
        origin: "Madagascar",
        fournisseur: "+261 34 79 476 16",
        stock: "14",
        price: "35",
        note: 2,
    },
    {
        id: 2,
        category: "informatique",
        titre: "Telephone Portable",
        image: "image.jpg",
        description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Quidem, odio minima odit placeat sapiente est omnis ducimus error qui voluptatum voluptas! Rem voluptatem magni ullam non facere dolorem iure modi.",
        origin: "Madagascar",
        fournisseur: "+261 34 79 476 16",
        stock: "14",
        price: "35",
        note: 2,
    },
    {
        id: 3,
        category: "informatique",
        titre: "Telephone Portable",
        image: "image.jpg",
        description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Quidem, odio minima odit placeat sapiente est omnis ducimus error qui voluptatum voluptas! Rem voluptatem magni ullam non facere dolorem iure modi.",
        origin: "Madagascar",
        fournisseur: "+261 34 79 476 16",
        stock: "14",
        price: "35",
        note: 3,
    },
    {
        id: 4,
        category: "informatique",
        titre: "Telephone Portable",
        image: "image.jpg",
        description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Quidem, odio minima odit placeat sapiente est omnis ducimus error qui voluptatum voluptas! Rem voluptatem magni ullam non facere dolorem iure modi.",
        origin: "Madagascar",
        fournisseur: "+261 34 79 476 16",
        stock: "14",
        price: "35",
        note: 2,
    },
    {
        id: 5,
        category: "informatique",
        titre: "Telephone Portable",
        image: "image.jpg",
        description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Quidem, odio minima odit placeat sapiente est omnis ducimus error qui voluptatum voluptas! Rem voluptatem magni ullam non facere dolorem iure modi.",
        origin: "Madagascar",
        fournisseur: "+261 34 79 476 16",
        stock: "14",
        price: "35",
        note: 4,
    },
    {
        id: 6,
        category: "Telephone",
        titre: "Telephone Portable",
        image: "image.jpg",
        description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Quidem, odio minima odit placeat sapiente est omnis ducimus error qui voluptatum voluptas! Rem voluptatem magni ullam non facere dolorem iure modi.",
        origin: "Madagascar",
        fournisseur: "+261 34 79 476 16",
        stock: "14",
        price: "35",
        note: 2,
    },
    {
        id: 7,
        category: "Telephone",
        titre: "Telephone Portable",
        image: "image.jpg",
        description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Quidem, odio minima odit placeat sapiente est omnis ducimus error qui voluptatum voluptas! Rem voluptatem magni ullam non facere dolorem iure modi.",
        origin: "Madagascar",
        fournisseur: "+261 34 79 476 16",
        stock: "14",
        price: "35",
        note: 2,
    },
    {
        id: 8,
        category: "Telephone",
        titre: "Telephone Portable",
        image: "image.jpg",
        description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Quidem, odio minima odit placeat sapiente est omnis ducimus error qui voluptatum voluptas! Rem voluptatem magni ullam non facere dolorem iure modi.",
        origin: "Madagascar",
        fournisseur: "+261 34 79 476 16",
        stock: "14",
        price: "35",
        note: 1,
    },
    {
        id: 9,
        category: "Telephone",
        titre: "Telephone Portable",
        image: "image.jpg",
        description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Quidem, odio minima odit placeat sapiente est omnis ducimus error qui voluptatum voluptas! Rem voluptatem magni ullam non facere dolorem iure modi.",
        origin: "Madagascar",
        fournisseur: "+261 34 79 476 16",
        stock: "14",
        price: "35",
        note: 2,
    },
    {
        id: 10,
        category: "Telephone",
        titre: "Telephone Portable",
        image: "image.jpg",
        description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Quidem, odio minima odit placeat sapiente est omnis ducimus error qui voluptatum voluptas! Rem voluptatem magni ullam non facere dolorem iure modi.",
        origin: "Madagascar",
        fournisseur: "+261 34 79 476 16",
        stock: "14",
        price: "35",
        note: 5,
    },
    {
        id: 11,
        category: "Telephone",
        titre: "Telephone Portable",
        image: "image.jpg",
        description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Quidem, odio minima odit placeat sapiente est omnis ducimus error qui voluptatum voluptas! Rem voluptatem magni ullam non facere dolorem iure modi.",
        origin: "Madagascar",
        fournisseur: "+261 34 79 476 16",
        stock: "14",
        price: "35",
        note: 2,
    },
    {
        id: 12,
        category: "Ordinateur",
        titre: "Telephone Portable",
        image: "image.jpg",
        description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Quidem, odio minima odit placeat sapiente est omnis ducimus error qui voluptatum voluptas! Rem voluptatem magni ullam non facere dolorem iure modi.",
        origin: "Madagascar",
        fournisseur: "+261 34 79 476 16",
        stock: "14",
        price: "35",
        note: 2,
    },
    {
        id: 13,
        category: "Ordinateur",
        titre: "Telephone Portable",
        image: "image.jpg",
        description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Quidem, odio minima odit placeat sapiente est omnis ducimus error qui voluptatum voluptas! Rem voluptatem magni ullam non facere dolorem iure modi.",
        origin: "Madagascar",
        fournisseur: "+261 34 79 476 16",
        stock: "14",
        price: "35",
        note: 3,
    },
    {
        id: 14,
        category: "Ordinateur",
        titre: "Telephone Portable",
        image: "image.jpg",
        description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Quidem, odio minima odit placeat sapiente est omnis ducimus error qui voluptatum voluptas! Rem voluptatem magni ullam non facere dolorem iure modi.",
        origin: "Madagascar",
        fournisseur: "+261 34 79 476 16",
        stock: "14",
        price: "35",
        note: 2,
    },
    {
        id: 15,
        category: "Ordinateur",
        titre: "Telephone Portable",
        image: "image.jpg",
        description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Quidem, odio minima odit placeat sapiente est omnis ducimus error qui voluptatum voluptas! Rem voluptatem magni ullam non facere dolorem iure modi.",
        origin: "Madagascar",
        fournisseur: "+261 34 79 476 16",
        stock: "14",
        price: "35",
        note: 3,
    },
    {
        id: 16,
        category: "Ordinateur",
        titre: "Telephone Portable",
        image: "image.jpg",
        description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Quidem, odio minima odit placeat sapiente est omnis ducimus error qui voluptatum voluptas! Rem voluptatem magni ullam non facere dolorem iure modi.",
        origin: "Madagascar",
        fournisseur: "+261 34 79 476 16",
        stock: "14",
        price: "35",
        note: 2,
    },
    {
        id: 17,
        category: "Ordinateur",
        titre: "Telephone Portable",
        image: "image.jpg",
        description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Quidem, odio minima odit placeat sapiente est omnis ducimus error qui voluptatum voluptas! Rem voluptatem magni ullam non facere dolorem iure modi.",
        origin: "Madagascar",
        fournisseur: "+261 34 79 476 16",
        stock: "14",
        price: "35",
        note: 4,
    },
    {
        id: 18,
        category: "Ordinateur",
        titre: "Telephone Portable",
        image: "image.jpg",
        description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Quidem, odio minima odit placeat sapiente est omnis ducimus error qui voluptatum voluptas! Rem voluptatem magni ullam non facere dolorem iure modi.",
        origin: "Madagascar",
        fournisseur: "+261 34 79 476 16",
        stock: "14",
        price: "35",
        note: 0,
    },
    {
        id: 19,
        category: "Appareil Photo",
        titre: "Telephone Portable",
        image: "image.jpg",
        description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Quidem, odio minima odit placeat sapiente est omnis ducimus error qui voluptatum voluptas! Rem voluptatem magni ullam non facere dolorem iure modi.",
        origin: "Madagascar",
        fournisseur: "+261 34 79 476 16",
        stock: "14",
        price: "35",
        note: 1,
    },
    {
        id: 20,
        category: "Appareil Photo",
        titre: "Telephone Portable",
        image: "image.jpg",
        description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Quidem, odio minima odit placeat sapiente est omnis ducimus error qui voluptatum voluptas! Rem voluptatem magni ullam non facere dolorem iure modi.",
        origin: "Madagascar",
        fournisseur: "+261 34 79 476 16",
        stock: "14",
        price: "35",
        note: 2,
    },
    {
        id: 21,
        category: "Appareil Photo",
        titre: "Telephone Portable",
        image: "image.jpg",
        description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Quidem, odio minima odit placeat sapiente est omnis ducimus error qui voluptatum voluptas! Rem voluptatem magni ullam non facere dolorem iure modi.",
        origin: "Madagascar",
        fournisseur: "+261 34 79 476 16",
        stock: "14",
        price: "35",
        note: 0,
    },
    {
        id: 22,
        category: "Appareil Photo",
        titre: "Telephone Portable",
        image: "image.jpg",
        description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Quidem, odio minima odit placeat sapiente est omnis ducimus error qui voluptatum voluptas! Rem voluptatem magni ullam non facere dolorem iure modi.",
        origin: "Madagascar",
        fournisseur: "+261 34 79 476 16",
        stock: "14",
        price: "35",
        note: 2,
    },
    {
        id: 23,
        category: "Appareil Photo",
        titre: "Telephone Portable",
        image: "image.jpg",
        description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Quidem, odio minima odit placeat sapiente est omnis ducimus error qui voluptatum voluptas! Rem voluptatem magni ullam non facere dolorem iure modi.",
        origin: "Madagascar",
        fournisseur: "+261 34 79 476 16",
        stock: "14",
        price: "35",
        note: 4,
    },
    {
        id: 24,
        category: "Appareil Photo",
        titre: "Telephone Portable",
        image: "image.jpg",
        description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Quidem, odio minima odit placeat sapiente est omnis ducimus error qui voluptatum voluptas! Rem voluptatem magni ullam non facere dolorem iure modi.",
        origin: "Madagascar",
        fournisseur: "+261 34 79 476 16",
        stock: "14",
        price: "35",
        note: 1,
    },
    {
        id: 25,
        category: "Appareil Photo",
        titre: "Telephone Portable",
        image: "image.jpg",
        description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Quidem, odio minima odit placeat sapiente est omnis ducimus error qui voluptatum voluptas! Rem voluptatem magni ullam non facere dolorem iure modi.",
        origin: "Madagascar",
        fournisseur: "+261 34 79 476 16",
        stock: "14",
        price: "35",
        note: 3,
    }
]