export const dataFake = [ ///titre, description, origin, fournisseur, stock, price, image
    {
        id: 1,
        category: "informatique",
        titre: "Projecteur",
        image: "image.jpg",
        description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Quidem, odio minima odit placeat sapiente est omnis ducimus error qui voluptatum voluptas! Rem voluptatem magni ullam non facere dolorem iure modi.",
        origin: "Madagascar",
        fournisseur: "+261 34 79 476 16",
        stock: "14",
        price: "35",
        note: 2,
    },
    {
        id: 2,
        category: "informatique",
        titre: "Modem/Flash",
        image: "image.jpg",
        description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Quidem, odio minima odit placeat sapiente est omnis ducimus error qui voluptatum voluptas! Rem voluptatem magni ullam non facere dolorem iure modi.",
        origin: "Madagascar",
        fournisseur: "+261 34 79 476 16",
        stock: "14",
        price: "35",
        note: 2,
    },
    {
        id: 3,
        category: "informatique",
        titre: "Onduleur",
        image: "image.jpg",
        description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Quidem, odio minima odit placeat sapiente est omnis ducimus error qui voluptatum voluptas! Rem voluptatem magni ullam non facere dolorem iure modi.",
        origin: "Madagascar",
        fournisseur: "+261 34 79 476 16",
        stock: "14",
        price: "35",
        note: 3,
    },
    {
        id: 4,
        category: "informatique",
        titre: "Clavier et Souris",
        image: "image.jpg",
        description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Quidem, odio minima odit placeat sapiente est omnis ducimus error qui voluptatum voluptas! Rem voluptatem magni ullam non facere dolorem iure modi.",
        origin: "Madagascar",
        fournisseur: "+261 34 79 476 16",
        stock: "14",
        price: "35",
        note: 2,
    },
    {
        id: 5,
        category: "informatique",
        titre: "Imprimante",
        image: "image.jpg",
        description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Quidem, odio minima odit placeat sapiente est omnis ducimus error qui voluptatum voluptas! Rem voluptatem magni ullam non facere dolorem iure modi.",
        origin: "Madagascar",
        fournisseur: "+261 34 79 476 16",
        stock: "14",
        price: "35",
        note: 4,
    },
    {
        id: 6,
        category: "Telephone",
        titre: "Nokia",
        image: "image.jpg",
        description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Quidem, odio minima odit placeat sapiente est omnis ducimus error qui voluptatum voluptas! Rem voluptatem magni ullam non facere dolorem iure modi.",
        origin: "Madagascar",
        fournisseur: "+261 34 79 476 16",
        stock: "14",
        price: "35",
        note: 2,
    },
    {
        id: 7,
        category: "Telephone",
        titre: "Iphone",
        image: "image.jpg",
        description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Quidem, odio minima odit placeat sapiente est omnis ducimus error qui voluptatum voluptas! Rem voluptatem magni ullam non facere dolorem iure modi.",
        origin: "Madagascar",
        fournisseur: "+261 34 79 476 16",
        stock: "14",
        price: "35",
        note: 2,
    },
    {
        id: 8,
        category: "Telephone",
        titre: "Aqous",
        image: "image.jpg",
        description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Quidem, odio minima odit placeat sapiente est omnis ducimus error qui voluptatum voluptas! Rem voluptatem magni ullam non facere dolorem iure modi.",
        origin: "Madagascar",
        fournisseur: "+261 34 79 476 16",
        stock: "14",
        price: "35",
        note: 1,
    },
    {
        id: 9,
        category: "Telephone",
        titre: "Sony/x-peria",
        image: "image.jpg",
        description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Quidem, odio minima odit placeat sapiente est omnis ducimus error qui voluptatum voluptas! Rem voluptatem magni ullam non facere dolorem iure modi.",
        origin: "Madagascar",
        fournisseur: "+261 34 79 476 16",
        stock: "14",
        price: "35",
        note: 2,
    },
    {
        id: 10,
        category: "Telephone",
        titre: "Read-me",
        image: "image.jpg",
        description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Quidem, odio minima odit placeat sapiente est omnis ducimus error qui voluptatum voluptas! Rem voluptatem magni ullam non facere dolorem iure modi.",
        origin: "Madagascar",
        fournisseur: "+261 34 79 476 16",
        stock: "14",
        price: "35",
        note: 5,
    },
    {
        id: 11,
        category: "Telephone",
        titre: "Window Phone",
        image: "image.jpg",
        description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Quidem, odio minima odit placeat sapiente est omnis ducimus error qui voluptatum voluptas! Rem voluptatem magni ullam non facere dolorem iure modi.",
        origin: "Madagascar",
        fournisseur: "+261 34 79 476 16",
        stock: "14",
        price: "35",
        note: 2,
    },
    {
        id: 12,
        category: "Ordinateur",
        titre: "Asus Rog ",
        image: "image.jpg",
        description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Quidem, odio minima odit placeat sapiente est omnis ducimus error qui voluptatum voluptas! Rem voluptatem magni ullam non facere dolorem iure modi.",
        origin: "Madagascar",
        fournisseur: "+261 34 79 476 16",
        stock: "14",
        price: "35",
        note: 2,
    },
    {
        id: 13,
        category: "Ordinateur",
        titre: "Accer/hp",
        image: "image.jpg",
        description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Quidem, odio minima odit placeat sapiente est omnis ducimus error qui voluptatum voluptas! Rem voluptatem magni ullam non facere dolorem iure modi.",
        origin: "Madagascar",
        fournisseur: "+261 34 79 476 16",
        stock: "14",
        price: "35",
        note: 3,
    },
    {
        id: 14,
        category: "Ordinateur",
        titre: "Dell Insipiron",
        image: "image.jpg",
        description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Quidem, odio minima odit placeat sapiente est omnis ducimus error qui voluptatum voluptas! Rem voluptatem magni ullam non facere dolorem iure modi.",
        origin: "Madagascar",
        fournisseur: "+261 34 79 476 16",
        stock: "14",
        price: "35",
        note: 2,
    },
    {
        id: 15,
        category: "Ordinateur",
        titre: "Mac Book Pro",
        image: "image.jpg",
        description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Quidem, odio minima odit placeat sapiente est omnis ducimus error qui voluptatum voluptas! Rem voluptatem magni ullam non facere dolorem iure modi.",
        origin: "Madagascar",
        fournisseur: "+261 34 79 476 16",
        stock: "14",
        price: "35",
        note: 3,
    },
    {
        id: 16,
        category: "Ordinateur",
        titre: "ThinkPad",
        image: "image.jpg",
        description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Quidem, odio minima odit placeat sapiente est omnis ducimus error qui voluptatum voluptas! Rem voluptatem magni ullam non facere dolorem iure modi.",
        origin: "Madagascar",
        fournisseur: "+261 34 79 476 16",
        stock: "14",
        price: "35",
        note: 2,
    },
    {
        id: 17,
        category: "Ordinateur",
        titre: "Dell Latitude",
        image: "image.jpg",
        description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Quidem, odio minima odit placeat sapiente est omnis ducimus error qui voluptatum voluptas! Rem voluptatem magni ullam non facere dolorem iure modi.",
        origin: "Madagascar",
        fournisseur: "+261 34 79 476 16",
        stock: "14",
        price: "35",
        note: 4,
    },
    {
        id: 18,
        category: "Ordinateur",
        titre: "Panasonic",
        image: "image.jpg",
        description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Quidem, odio minima odit placeat sapiente est omnis ducimus error qui voluptatum voluptas! Rem voluptatem magni ullam non facere dolorem iure modi.",
        origin: "Madagascar",
        fournisseur: "+261 34 79 476 16",
        stock: "14",
        price: "35",
        note: 0,
    },
    {
        id: 19,
        category: "Appareil Photo",
        titre: "Nikon",
        image: "image.jpg",
        description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Quidem, odio minima odit placeat sapiente est omnis ducimus error qui voluptatum voluptas! Rem voluptatem magni ullam non facere dolorem iure modi.",
        origin: "Madagascar",
        fournisseur: "+261 34 79 476 16",
        stock: "14",
        price: "35",
        note: 1,
    },
    {
        id: 20,
        category: "Appareil Photo",
        titre: "Canon",
        image: "image.jpg",
        description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Quidem, odio minima odit placeat sapiente est omnis ducimus error qui voluptatum voluptas! Rem voluptatem magni ullam non facere dolorem iure modi.",
        origin: "Madagascar",
        fournisseur: "+261 34 79 476 16",
        stock: "14",
        price: "35",
        note: 2,
    },
    {
        id: 21,
        category: "Appareil Photo",
        titre: "Pixel",
        image: "image.jpg",
        description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Quidem, odio minima odit placeat sapiente est omnis ducimus error qui voluptatum voluptas! Rem voluptatem magni ullam non facere dolorem iure modi.",
        origin: "Madagascar",
        fournisseur: "+261 34 79 476 16",
        stock: "14",
        price: "35",
        note: 0,
    },
    {
        id: 22,
        category: "Appareil Photo",
        titre: "IPhone X",
        image: "image.jpg",
        description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Quidem, odio minima odit placeat sapiente est omnis ducimus error qui voluptatum voluptas! Rem voluptatem magni ullam non facere dolorem iure modi.",
        origin: "Madagascar",
        fournisseur: "+261 34 79 476 16",
        stock: "14",
        price: "35",
        note: 2,
    },
    {
        id: 23,
        category: "Appareil Photo",
        titre: "Objectif",
        image: "image.jpg",
        description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Quidem, odio minima odit placeat sapiente est omnis ducimus error qui voluptatum voluptas! Rem voluptatem magni ullam non facere dolorem iure modi.",
        origin: "Madagascar",
        fournisseur: "+261 34 79 476 16",
        stock: "14",
        price: "35",
        note: 4,
    },
    {
        id: 24,
        category: "Appareil Photo",
        titre: "Zooming",
        image: "image.jpg",
        description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Quidem, odio minima odit placeat sapiente est omnis ducimus error qui voluptatum voluptas! Rem voluptatem magni ullam non facere dolorem iure modi.",
        origin: "Madagascar",
        fournisseur: "+261 34 79 476 16",
        stock: "14",
        price: "35",
        note: 1,
    },
    {
        id: 25,
        category: "Appareil Photo",
        titre: "Drônne",
        image: "image.jpg",
        description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Quidem, odio minima odit placeat sapiente est omnis ducimus error qui voluptatum voluptas! Rem voluptatem magni ullam non facere dolorem iure modi.",
        origin: "Madagascar",
        fournisseur: "+261 34 79 476 16",
        stock: "14",
        price: "35",
        note: 3,
    }
]